// This file was auto-generated by Fern from our API Definition.

package client

import (
	http "net/http"

	core "github.com/skyflowapi/skyflow-go/core"
	flowservice "github.com/skyflowapi/skyflow-go/flowservice"
	internal "github.com/skyflowapi/skyflow-go/internal"
	option "github.com/skyflowapi/skyflow-go/option"
	records "github.com/skyflowapi/skyflow-go/records"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Records     *records.Client
	Flowservice *flowservice.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:      options.ToHeader(),
		Records:     records.NewClient(opts...),
		Flowservice: flowservice.NewClient(opts...),
	}
}
