version: "2"

run:
  timeout: 5m
  tests: false
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - revive
    - goconst
  exclusions:
    paths:
      - internal/generated
      - test

  settings:
    revive:
      enable-all-rules: false
      enable-default-rules: false
      rules:
        - name: add-constant
          severity: warning
          disabled: false
          arguments:
            - max-lit-count: "1"
              allow-strs: '""'
              allow-ints: "0,1,2,64,0644"
              allow-floats: "0.0,0.,1.0,1.,2.0,2."
        
        - name: var-naming
          arguments:
            - ["ID", "URL", "API", "HTTP", "JSON", "UUID"]
            - []
            - - upper-case-const: true
                skip-package-name-checks: true
        - name: receiver-naming
        
        - name: unexported-return
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: redefines-builtin-id
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: dot-imports
          disabled: true
        - name: indent-error-flow
          disabled: true
    
    goconst:
      min-len: 1
      min-occurrences: 1
      match-constant: true
      numbers: true