// Code generated by Fern. DO NOT EDIT.

package records

import (
	context "context"
	http "net/http"

	skyflow "github.com/skyflowapi/skyflow-go/api"
	core "github.com/skyflowapi/skyflow-go/core"
	internal "github.com/skyflowapi/skyflow-go/internal"
	option "github.com/skyflowapi/skyflow-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Executes a query on the specified vault.
func (c *Client) RecordServiceExecuteQuery(
	ctx context.Context,
	request *skyflow.ExecuteQueryRequest,
	opts ...option.RequestOption,
) (*skyflow.ExecuteQueryResponse, error) {
	response, err := c.WithRawResponse.RecordServiceExecuteQuery(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
