// This file was auto-generated by Fern from our API Definition.

package records

import (
	context "context"
	http "net/http"

	skyflowgo "github.com/skyflowapi/skyflow-go/api"
	core "github.com/skyflowapi/skyflow-go/core"
	internal "github.com/skyflowapi/skyflow-go/internal"
	option "github.com/skyflowapi/skyflow-go/option"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Executes a query on the specified vault.
func (c *Client) FlowServiceExecuteQuery(
	ctx context.Context,
	request *skyflowgo.V1ExecuteQueryRequest,
	opts ...option.RequestOption,
) (*skyflowgo.V1ExecuteQueryResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"",
	)
	endpointURL := baseURL + "/v2/query"
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	headers.Set("Content-Type", "application/json")

	var response *skyflowgo.V1ExecuteQueryResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
