// Code generated by Fern. DO NOT EDIT.

package records

import (
	context "context"
	http "net/http"

	core "github.com/skyflowapi/skyflow-go/core"
	internal "github.com/skyflowapi/skyflow-go/internal"
	option "github.com/skyflowapi/skyflow-go/option"
	skyflow "github.com/skyflowapi/skyflow-go/api"

)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

func (r *RawClient) RecordServiceExecuteQuery(
	ctx context.Context,
	request *skyflow.ExecuteQueryRequest,
	opts ...option.RequestOption,
) (*core.Response[*skyflow.ExecuteQueryResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"",
	)
	endpointURL := baseURL + "/v2/query"
	headers := internal.MergeHeaders(
		r.header.Clone(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *skyflow.ExecuteQueryResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*skyflow.ExecuteQueryResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
