package errors

const sdk_name = "Skyflow Go SDK "
const sdk_version = "v2"
const sdk_prefix = sdk_name + sdk_version

// TO DO
const (
	VAULT_ID_ALREADY_IN_CONFIG_LIST      string = sdk_prefix + " Validation error. VaultId is present in an existing config. Specify a new vaultId in config."
	VAULT_ID_NOT_IN_CONFIG_LIST          string = sdk_prefix + " Validation error. VaultId is missing from the config. Specify the vaultIds from configs."
	CONNECTION_ID_ALREADY_IN_CONFIG_LIST string = sdk_prefix + " Validation error. ConnectionId is present in an existing config. Specify a connectionId in config."
	CONNECTION_ID_NOT_IN_CONFIG_LIST     string = sdk_prefix + " Validation error. ConnectionId is missing from the config. Specify the connectionIds from configs."
	EMPTY_CREDENTIALS                    string = sdk_prefix + " Validation error. Invalid credentials. Specify a valid credentials."

	INVALID_VAULT_ID   string = sdk_prefix + " Initialization failed. Invalid vault ID. Specify a valid vault ID."
	EMPTY_VAULT_ID     string = sdk_prefix + " Initialization failed. Invalid vault ID. Vault ID must not be empty."
	INVALID_CLUSTER_ID string = sdk_prefix + " Initialization failed. Invalid cluster ID. Specify cluster ID."
	EMPTY_CLUSTER_ID   string = sdk_prefix + " Initialization failed. Invalid cluster ID. Specify a valid cluster ID."

	EMPTY_CONNECTION_ID           string = sdk_prefix + " Initialization failed. Invalid connection ID. Connection ID must not be empty."
	INVALID_CONNECTION_URL        string = sdk_prefix + " Initialization failed. Invalid connection URL. Specify a valid connection URL."
	EMPTY_CONNECTION_URL          string = sdk_prefix + " Initialization failed. Invalid connection URL. Connection URL must not be empty."
	INVALID_CONNECTION_URL_FORMAT string = sdk_prefix + " Initialization failed. Connection URL is not a valid URL. Specify a valid connection URL."

	MULTIPLE_TOKEN_GENERATION_MEANS_PASSED string = sdk_prefix + " Initialization failed. Invalid credentials. Specify only one from 'path', 'credentialsString', 'token' or 'apiKey'."
	NO_TOKEN_GENERATION_MEANS_PASSED       string = sdk_prefix + " Initialization failed. Invalid credentials. Specify any one from 'path', 'credentialsString', 'token' or 'apiKey'."
	EMPTY_CREDENTIAL_FILE_PATH             string = sdk_prefix + " Initialization failed. Invalid credentials. Credentials file path must not be empty."
	EMPTY_CREDENTIALS_STRING               string = sdk_prefix + " Initialization failed. Invalid credentials. Credentials string must not be empty."
	EMPTY_TOKEN                            string = sdk_prefix + " Initialization failed. Invalid credentials. Token must not be empty."
	EMPTY_API_KEY                          string = sdk_prefix + " Initialization failed. Invalid credentials. Api key must not be empty."
	INVALID_API_KEY                        string = sdk_prefix + " Initialization failed. Invalid credentials. Specify valid api key."
	EMPTY_ROLES                            string = sdk_prefix + " Initialization failed. Invalid roles. Specify at least one role."
	EMPTY_ROLE_IN_ROLES                    string = sdk_prefix + " Initialization failed. Invalid role. Specify a valid role."
	EMPTY_CONTEXT                          string = sdk_prefix + " Initialization failed. Invalid context. Specify a valid context."

	FILE_NOT_FOUND                  string = sdk_prefix + " Initialization failed. Credential file not found at %s. Verify the file path."
	FILE_INVALID_JSON               string = sdk_prefix + " Initialization failed. File at %s is not in valid JSON format. Verify the file contents."
	CREDENTIALS_STRING_INVALID_JSON string = sdk_prefix + " Initialization failed. Credentials string is not in valid JSON format. Verify the credentials string contents."
	INVALID_CREDENTIALS             string = sdk_prefix + " Initialization failed. Invalid credentials provided. Specify valid credentials."
	MISSING_PRIVATE_KEY             string = sdk_prefix + " Initialization failed. Unable to read private key in credentials. Verify your private key."
	MISSING_CLIENT_ID               string = sdk_prefix + " Initialization failed. Unable to read client ID in credentials. Verify your client ID."
	MISSING_KEY_ID                  string = sdk_prefix + " Initialization failed. Unable to read key ID in credentials. Verify your key ID."
	MISSING_TOKEN_URI               string = sdk_prefix + " Initialization failed. Unable to read token URI in credentials. Verify your token URI."
	INVALID_TOKEN_URI               string = sdk_prefix + " Initialization failed. Token URI in not a valid URL in credentials. Verify your token URI."
	JWT_INVALID_FORMAT              string = sdk_prefix + " Initialization failed. Invalid private key format. Verify your credentials."
	INVALID_ALGORITHM               string = sdk_prefix + " Initialization failed. Invalid algorithm to parse private key. Specify valid algorithm."
	INVALID_KEY_SPEC                string = sdk_prefix + " Initialization failed. Unable to parse RSA private key. Verify your credentials."
	JWT_DECODE_ERROR                string = sdk_prefix + " Validation error. Invalid access token. Verify your credentials."
	MISSING_ACCESS_TOKEN            string = sdk_prefix + " Validation error. Access token not present in the response from bearer token generation. Verify your credentials."
	MISSING_TOKEN_TYPE              string = sdk_prefix + " Validation error. Token type not present in the response from bearer token generation. Verify your credentials."

	TABLE_KEY_ERROR                                   string = sdk_prefix + " Validation error. 'table' key is missing from the payload. Specify a 'table' key."
	EMPTY_TABLE                                       string = sdk_prefix + " Validation error. 'table' can't be empty. Specify a table."
	VALUES_KEY_ERROR                                  string = sdk_prefix + " Validation error. 'values' key is missing from the payload. Specify a 'values' key."
	EMPTY_VALUES                                      string = sdk_prefix + " Validation error. 'values' can't be empty. Specify values."
	EMPTY_KEY_IN_VALUES                               string = sdk_prefix + " Validation error. Invalid key in values. Specify a valid key."
	EMPTY_VALUE_IN_VALUES                             string = sdk_prefix + " Validation error. Invalid value in values. Specify a valid value."
	TOKENS_KEY_ERROR                                  string = sdk_prefix + " Validation error. 'tokens' key is missing from the payload. Specify a 'tokens' key."
	EMPTY_TOKENS                                      string = sdk_prefix + " Validation error. The 'tokens' field is empty. Specify tokens for one or more fields."
	EMPTY_KEY_IN_TOKENS                               string = sdk_prefix + " Validation error. Invalid key tokens. Specify a valid key."
	EMPTY_VALUE_IN_TOKENS                             string = sdk_prefix + " Validation error. Invalid value in tokens. Specify a valid value."
	EMPTY_UPSERT                                      string = sdk_prefix + " Validation error. 'upsert' key can't be empty. Specify an upsert column."
	HOMOGENOUS_NOT_SUPPORTED_WITH_UPSERT              string = sdk_prefix + " Validation error. 'homogenous' is not supported with 'upsert'. Specify either 'homogenous' or 'upsert'."
	TOKENS_PASSED_FOR_BYOT_DISABLE                    string = sdk_prefix + " Validation error. 'TokenMode' wasn't specified. Set 'TokenMode' to 'ENABLE' to insert tokens."
	NO_TOKENS_WITH_BYOT                               string = sdk_prefix + " Validation error. Tokens weren't specified for records while 'TokenMode' was %s. Specify tokens."
	MISMATCH_OF_FIELDS_AND_TOKENS                     string = sdk_prefix + " Validation error. 'fields' and 'tokens' have different columns names. Verify that 'fields' and 'tokens' columns match."
	INSUFFICIENT_TOKENS_PASSED_FOR_BYOT_ENABLE_STRICT string = sdk_prefix + " Validation error. 'TokenMode' is set to 'ENABLE_STRICT' or 'ENABLE', but some fields are missing tokens. Specify tokens for all fields."
	BATCH_INSERT_PARTIAL_SUCCESS                      string = sdk_prefix + " Insert operation completed with partial success."
	BATCH_INSERT_FAILURE                              string = sdk_prefix + " Insert operation failed."
	MISMATCH_OF_FIELDS_AND_VALUES                     string = sdk_prefix + " Validation error. 'fields' and 'values' have different columns names. Verify that 'fields' and 'values' columns match."
	MISMATCH_OF_FIELDS_AND_OPTIONS                    string = sdk_prefix + " Validation error. 'fields' and 'options' have different columns names. Verify that 'fields' and 'options' columns match."
	INVALID_OPTION                                    string = sdk_prefix + " Validation error. Invalid options were specified in the payload. Specify valid options."

	EMPTY_PARAMETERS      string = sdk_prefix + " Validation error. Parameters must not be empty. Specify valid parameters."
	EMPTY_PARAMETER_NAME  string = sdk_prefix + " Validation error. Parameter name is missing in parameters. Specify a valid name."
	EMPTY_PARAMETER_VALUE string = sdk_prefix + " Validation error. Parameter value is missing for name. Specify a valid value."

	INVALID_TABLE     string = sdk_prefix + " Validation error. Invalid table. Specify a valid table."
	EMPTY_COLUMNS     string = sdk_prefix + " Validation error. Columns can't be empty. Specify valid columns."
	EMPTY_COLUMN_NAME string = sdk_prefix + " Validation error. Invalid column name. Specify valid column names."

	EMPTY_ROWS        string = sdk_prefix + " Validation error. Rows can't be empty. Specify valid rows."
	EMPTY_ROW_KEY     string = sdk_prefix + " Validation error. Rows have invalid keys. Specify valid keys."
	EMPTY_ROW_VALUE   string = sdk_prefix + " Validation error. Rows have invalid values. Specify valid values."
	INVALID_DATA_TYPE string = sdk_prefix + " Validation error. Invalid data type specified for column '%s'. Specify a valid data type."

	MULTIPLE_ERRORS          string = sdk_prefix + " Multiple validation errors found. Refer to individual errors for more details."
	GENERAL_VALIDATION_ERROR string = sdk_prefix + " 	Validation error. Please check your input and try again."

	REQUEST_ID_MISSING string = sdk_prefix + " Request failed. Request ID is missing in the response."
	SERVER_ERROR       string = sdk_prefix + " Server error. Please try again later."
	INVALID_RESPONSE   string = sdk_prefix + " Error while parsing server response. Please verify the response."
	TIMEOUT_ERROR      string = sdk_prefix + " Request timed out. Please try again later."

	OPERATION_NOT_SUPPORTED       string = sdk_prefix + " Operation failed. The operation is not supported for the specified parameters."
	INVALID_AUTHENTICATION_METHOD string = sdk_prefix + " Authentication error. Invalid authentication method specified. Use a supported method."

	UNAUTHORIZED_ACCESS     string = sdk_prefix + " Authorization error. You do not have permission to perform this operation."
	FORBIDDEN_OPERATION     string = sdk_prefix + " Authorization error. The operation is forbidden for the current credentials."
	RESOURCE_NOT_FOUND      string = sdk_prefix + " Resource error. The requested resource could not be found. Please verify the resource."
	RESOURCE_CONFLICT       string = sdk_prefix + " Resource error. Conflict detected while accessing the resource. Please resolve the conflict and try again."
	RESOURCE_LIMIT_EXCEEDED string = sdk_prefix + " Resource error. The resource limit has been exceeded. Please contact support."

	INTERNAL_SDK_ERROR                    string = sdk_prefix + " Internal SDK error. Please contact support with the error details."
	FEATURE_NOT_IMPLEMENTED               string = sdk_prefix + " Feature error. This feature is not implemented in the current version. Please upgrade to a supported version."
	EMPTY_REQUEST_HEADER                  string = sdk_prefix + " Validation error. Request headers are empty. Specify valid request headers."
	INVALID_REQUEST_HEADERS               string = sdk_prefix + "Validation error. Request headers aren't valid. Specify valid request headers."
	INVALID_QUERY_PARAM                   string = sdk_prefix + " Validation error. Query parameters aren't valid. Specify valid query parameters."
	EMPTY_QUERY_PARAM                     string = sdk_prefix + " Validation error. Query parameters are empty. Specify valid query parameters."
	INVALID_REQUEST_BODY                  string = sdk_prefix + " Validation error. Invalid request body. Specify the request body as an object."
	EMPTY_REQUEST_BODY                    string = sdk_prefix + " Validation error. Request body can't be empty. Specify a valid request body."
	TOKENS_REQUIRED                       string = sdk_prefix + " Invalid %s request. Tokens are required."
	EMPTY_TOKENS_DETOKENIZE               string = sdk_prefix + " Validation error. Invalid data tokens. Specify at least one data token."
	INVALID_DATA_TOKENS                   string = sdk_prefix + " Validation error. Invalid data tokens. Specify valid data tokens."
	EMPTY_TOKEN_IN_DATA_TOKEN             string = sdk_prefix + " Validation error. Invalid data tokens. Specify a valid data token."
	IDS_KEY_ERROR                         string = sdk_prefix + " Validation error. 'ids' key is missing from the payload. Specify an 'ids' key."
	EMPTY_IDS                             string = sdk_prefix + " Validation error. 'ids' can't be empty. Specify at least one id."
	EMPTY_ID_IN_IDS                       string = sdk_prefix + " Validation error. Invalid id in 'ids'. Specify a valid id."
	EMPTY_FIELDS                          string = sdk_prefix + " Validation error. Fields are empty in get payload. Specify at least one field."
	EMPTY_FIELD_IN_FIELDS                 string = sdk_prefix + " Validation error. Invalid field in 'fields'. Specify a valid field."
	REDACTION_KEY_ERROR                   string = sdk_prefix + " Validation error. 'redaction' key is missing from the payload. Specify a 'redaction' key."
	REDACTION_WITH_TOKENS_NOT_SUPPORTED   string = sdk_prefix + " Validation error. 'redaction' can't be used when 'returnTokens' is specified. Remove 'redaction' from payload if 'returnTokens' is specified."
	TOKENS_GET_COLUMN_NOT_SUPPORTED       string = sdk_prefix + " Validation error. Column name and/or column values can't be used when 'returnTokens' is specified. Remove unique column values or 'returnTokens' from the payload."
	EMPTY_OFFSET                          string = sdk_prefix + " Validation error. 'offset' can't be empty. Specify an offset."
	EMPTY_LIMIT                           string = sdk_prefix + " Validation error. 'limit' can't be empty. Specify a limit."
	UNIQUE_COLUMN_OR_IDS_KEY_ERROR        string = sdk_prefix + " Validation error. 'ids' or 'columnName' key is missing from the payload. Specify the ids or unique 'columnName' in payload."
	BOTH_IDS_AND_COLUMN_DETAILS_SPECIFIED string = sdk_prefix + " Validation error. Both Skyflow IDs and column details can't be specified. Either specify Skyflow IDs or unique column details."
	COLUMN_NAME_KEY_ERROR                 string = sdk_prefix + " Validation error. 'columnName' isn't specified whereas 'columnValues' are specified. Either add 'columnName' or remove 'columnValues'."
	EMPTY_COLUMN_NAME_GET                 string = sdk_prefix + " Validation error. 'columnName' can't be empty. Specify a column name."
	COLUMN_VALUES_KEY_ERROR_GET           string = sdk_prefix + " Validation error. 'columnValues' aren't specified whereas 'columnName' is specified. Either add 'columnValues' or remove 'columnName'."
	EMPTY_COLUMN_VALUES                   string = sdk_prefix + " Validation error. 'columnValues' can't be empty. Specify at least one column value"
	EMPTY_VALUE_IN_COLUMN_VALUES          string = sdk_prefix + " Validation error. Invalid value in column values. Specify a valid column value."
	TOKEN_KEY_ERROR                       string = sdk_prefix + " Validation error. 'token' key is missing from the payload. Specify a 'token' key."
	PARTIAL_SUCCESS                       string = sdk_prefix + " Validation error. Check 'SkyflowError.data' for details."
	QUERY_KEY_ERROR                       string = sdk_prefix + " Validation error. 'query' key is missing from the payload. Specify a 'query' key."
	EMPTY_QUERY                           string = sdk_prefix + " Validation error. 'query' can't be empty."
	COLUMN_VALUES_KEY_ERROR_TOKENIZE      string = sdk_prefix + " Validation error. 'columnValues' key is missing from the payload. Specify a 'columnValues' key."
	VALUES_IS_REQUIRED_TOKENIZE           string = sdk_prefix + " Validation error. Invalid tokenize request. Values are required."
	EMPTY_COLUMN_GROUP_IN_COLUMN_VALUES   string = sdk_prefix + " Validation error. Invalid tokenize request. Column group can not be null or empty in column values at index %s."

	// tokenize
	MISSING_VALUES_IN_TOKENIZE       string = sdk_prefix + " Validation error. Values cannot be empty in tokenize request. Specify valid values."
	INVALID_VALUES_TYPE_IN_TOKENIZE  string = sdk_prefix + " Validation error. Invalid values type in tokenize request. Specify valid values of type array."
	EMPTY_VALUES_IN_TOKENIZE         string = sdk_prefix + " Validation error. Values array cannot be empty. Specify value's in tokenize request."
	EMPTY_DATA_IN_TOKENIZE           string = sdk_prefix + " Validation error. Data cannot be empty in tokenize request. Specify a valid data at index %s."
	INVALID_DATA_IN_TOKENIZE         string = sdk_prefix + " Validation error. Invalid Data. Specify a valid data at index %s."
	INVALID_COLUMN_GROUP_IN_TOKENIZE string = sdk_prefix + " Validation error. Invalid type of column group passed in tokenize request. Column group must be of type string at index %s."
	INVALID_VALUE_IN_TOKENIZE        string = sdk_prefix + " Validation error. Invalid type of value passed in tokenize request. Value must be of type string at index %s."
	INVALID_TOKENIZE_REQUEST         string = sdk_prefix + " Validation error. Invalid tokenize request. Specify a valid tokenize request."
	EMPTY_COLUMN_GROUP_IN_TOKENIZE   string = sdk_prefix + " Validation error. Column group cannot be empty in tokenize request. Specify a valid column group at index %s."
	EMPTY_VALUE_IN_TOKENIZE          string = sdk_prefix + " Validation error. Value cannot be empty in tokenize request. Specify a valid value at index %s."

	// update
	EMPTY_ID_IN_UPDATE string = sdk_prefix + " Validation error. 'id' can't be empty. Specify an id."
)
