name: "EndorLabs Scan"
# Run workflow each time code is pushed to your repository and on a schedule.
on:
  pull_request:
    branches:
      - main
jobs:
  scan-repo:
    runs-on: ubuntu-latest 
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'  
        - name: Go Build 
          run: |
            go mod tidy
            go mod vendor          
        - name: Endor Labs SCA Scan
          uses: endorlabs/github-action@main
          with:
            namespace: "skyflow"
            api: "https://api.endorlabs.com"
            enable_github_action_token: true
            scan_dependencies: true
            pr: true
            enable_pr_comments: true
            github_token: ${{ secrets.REPO_PAT_SERVICE_IT }} #<-- Needs to be enabled if you want to use enable_pr_comments
            additional_args: "--pr-incremental"
