name: GoSec
# Run workflow each time code is pushed to your repository.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Security Scan
      uses: securego/gosec@master
      with:
        # we let the report trigger content trigger a failure using the GitHub Security features.
        args: '-severity=high -confidence medium -no-fail -fmt sarif -out results.sarif ./...'
        # run: time gosec ./...

    - name: Generate GoSec Report
      run: |
        # Command to generate a report from the SARIF output
         -fmt json > gosec_report.json
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

    - name: Upload GoSec results
      uses: actions/upload-artifact@v4
      with:
          name: results
          path: results.sarif
