name: GoSec
# Run workflow each time code is pushed to your repository.
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Security Scan
      uses: securego/gosec@v2.20.0
      with:
        # we let the report trigger content trigger a failure using the GitHub Security features.
         args: '-severity=high -confidence=high -no-fail  -fmt json -out results.json ./...' 
        # run: time gosec ./...
        
    - name: Display Raw GoSec JSON Output
      run: |
        echo "Displaying raw GoSec results..."
        cat results.json
        
    - name: Inspect the Structure of JSON 
      run: |
        # Let's display the 'Issues' array to understand its structure
        echo "Inspecting the Issues structure..."
        jq '.Issues' results.json
     
